### ISSUE TITLE
Unable to display js alerts seemingly

### ISSUE THREAD

**Issue by littlepeace2005** [Aurorum-Studio/flarum-app#6] opened 2023-04-05 18:11 UTC
Message boxes cannot be displayed. This probably causes the problem that one may open a text editor but cannot close it.

**Comment by Aurorum-Studio** [comment] 2023-04-06 02:21
Hi, this seems to be caused by the status/version of the webview of the device, would you mind uploading a screenshot, so I can be more clear about what's wrong.

**Comment by Aurorum-Studio** [comment] 2023-04-10 14:32
Hello, emm, can you provide the status info, or screenshot, so I can help you, if you don't reply me in a week, I'll close this issue. 🦊. Thank you for using this project.

**Comment by Aurorum-Studio** [comment] 2023-06-17 14:07
I haven't received any further information, this issue is closed.

**Closed by Aurorum-Studio** 2023-06-17 14:07 UTC
